import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Mike's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-red-500'>Lets build a AWESOME web3 portfolio</h1>
    </div>
  )
}
